name <- readline(prompt = "Enter your name: ")
age <- as.integer(readline(prompt = "Enter your age: "))
cat("Name:", name, "\n")
cat("Age:", age, "\n")
cat("R version:", R.version$version.string, "\n")